steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [
            'build',
            '-t', 'gcr.io/eye-guide/pdf-processor-service',
            '.'
        ]
images:
- 'gcr.io/eye-guide/pdf-processor-service'
