import json
from PIL import Image
from pathlib import Path
import torch
import torch.nn as nn
import torch.optim as optim
import torchvision.transforms as T
from torch.utils.data import Dataset, DataLoader


class FontsDataset(Dataset):
    def __init__(self, folder):
        """
        Initializes the dataset by loading images and labels from a folder generated by extract.generate_training_data.
        """
        self.images = []
        self.labels = []
        self.classes = {}
        for path, folders, files in Path(folder).walk():
            for file in files:
                if file.endswith(".png"):
                    img = Image.open(path / file)
                    t = img_to_tensor(img)
                    self.images.append(t)
                    label_str = path.parent.name
                    if label_str not in self.classes:
                        self.classes[label_str] = len(self.classes)
                    self.labels.append(self.classes[label_str])

    def __len__(self):
        return len(self.images)

    def __getitem__(self, idx):
        return self.images[idx], self.labels[idx]


def img_to_tensor(img: Image.Image) -> torch.Tensor:
    t = T.ToTensor()(img)
    t = 2 * (1 - t) - 1
    return t


class Net(nn.Module):
    def __init__(self, num_classes: int):
        """
        :param num_classes: must match the number of subfolders in the training data folder
        """
        super().__init__()
        self.net = nn.Sequential(
            nn.Conv2d(1, 8, 5),
            nn.ReLU(),
            nn.MaxPool2d(2, 2),
            nn.Conv2d(8, 16, 5),
            nn.ReLU(),
            nn.MaxPool2d(2, 2),
            nn.Conv2d(16, 32, 5),
            nn.ReLU(),
            nn.MaxPool2d(2, 2),
            nn.Conv2d(32, 64, 5),
            nn.ReLU(),
            nn.MaxPool2d(2, 2),
            nn.Flatten(),
            nn.Linear(1024, 341),
            nn.ReLU(),
            nn.Linear(341, 113),
            nn.ReLU(),
            nn.Linear(113, num_classes),
        )

    def forward(self, x):
        return self.net(x)


def train_model(model: nn.Module, dataloader: DataLoader, epochs: int = 10):
    criterion = nn.CrossEntropyLoss()
    optimizer = optim.Adam(model.parameters(), lr=0.001)
    model.train()
    for epoch in range(epochs):
        total_loss = 0
        correct = 0
        total = 0
        for x, y in dataloader:
            optimizer.zero_grad()
            output = model(x)
            loss = criterion(output, y)
            loss.backward()
            optimizer.step()
            total_loss += loss.item()

            preds = output.argmax(dim=1)
            correct += (preds == y).sum().item()
            total += y.size(0)

        print(f"Epoch {epoch+1:02d}: Loss={total_loss:.4f}, Accuracy={correct/total:.2%}")


def eval_model(model: nn.Module, dataloader: DataLoader):
    model.eval()
    correct = 0
    total = 0
    with torch.no_grad():
        for x, y in dataloader:
            output = model(x)
            preds = output.argmax(dim=1)
            correct += (preds == y).sum().item()
            total += y.size(0)
    return {
        "accuracy": correct / total,
        "total": total,
        "correct": correct,
    }


if __name__ == "__main__":
    dataset = FontsDataset("ml/font/training_data")
    train_dataset, eval_dataset = torch.utils.data.random_split(dataset, [0.8, 0.2])
    train_loader = DataLoader(train_dataset, batch_size=32, shuffle=True)
    eval_loader = DataLoader(eval_dataset, batch_size=32, shuffle=False)

    model = Net(7)
    train_model(model, train_loader, 20)

    torch.save(model.state_dict(), "ml/font/model.pth")
    with open("ml/font/classes.json", "w") as f:
        json.dump(dataset.classes, f)

    eval_results = eval_model(model, eval_loader)
    print(eval_results)
